export const NETWORK_CALL = 'NETWORK_CALL';
export const API_PAGINATION = 'API_PAGINATION';
export const SET_CONTACTS = 'SET_CONTACTS';
export const SET_CONTACTS_PAGINATION = 'SET_CONTACTS_PAGINATION';